### ISSUE TITLE
aerofiles.xcsoar.ObservationZone object

### ISSUE THREAD

**Issue by scls19fr** [Turbo87/aerofiles#15]
Hello,

it will be nice to have a `aerofiles.xcsoar.ObservationZone object` which could be passed to `xcsoar.Writer.write_observation_zone`. It will reduce my code https://github.com/scls19fr/pycondor/blob/master/pycondor/pycondor2xcsoar6.py
and improve it's readability

An implementation of this could be like this:

```
class ObservationZone:
    def __init__(self, **kw):
        assert 'type' in kw

        self.type = kw['type']

        if kw['type'] == ObservationZoneType.LINE:
            assert 'length' in kw
            self.length = kw['length']

        elif kw['type'] == ObservationZoneType.CYLINDER:
            assert 'radius' in kw
            self.radius = kw['radius']

        elif kw['type'] == ObservationZoneType.SECTOR:
            assert 'radius' in kw
            assert 'start_radial' in kw
            assert 'end_radial' in kw
            self.radius = kw['radius']
            self.start_radial = kw['start_radial']
            self.end_radial = kw['end_radial']

        elif kw['type'] == ObservationZoneType.SYMMETRIC_QUADRANT:
            assert 'radius' in kw
            self.radius = kw['radius']

        elif kw['type'] == ObservationZoneType.CUSTOM_KEYHOLE:
            assert 'radius' in kw
            assert 'inner_radius' in kw
            assert 'angle' in kw
            self.radius = kw['radius']
            self.inner_radius = kw['inner_radius']
            self.angle = kw['angle']

    def __str__(self):
        s = self.type + " "
        for key, val in self.__dict__.items():
            if key!="type":
                s += "%s: %s" % (key, val)
        return(s)
```

And 
    def write_observation_zone(self, **kw):

(in https://github.com/Turbo87/aerofiles/blob/master/aerofiles/xcsoar/writer.py )

should accept both either keyword args or an ObservationZone object.

so it could be 

```
def write_observation_zone(self, obj=None, **kw):
    if obj is None:
        obj = ObservationZone(**kw)

    self.write_tag('ObservationZone', **obj.__dict__)
```

Kind regards

**Comment by bubeck** [comment]
You are proposing to use objects as parameters to methods instead of individual values. I completely agree, that this is a better way to structure aerofiles. However, aerofiles currently uses values and not parameters for all their methods. So I dont see a good reason, why we should _only_ change ObservationZone to OO and keep all other methods handling values.

So either we go completely OO or nowhere, otherwise we have two different types of parameter passing, which leads to irritation.

Going completely to OO would be a big change. It would be either duplication of code (as you propose) or incompatible (if we drop parameter values).

So I would currently not follow your proposed change, for the above reasons. Did I oversee something?
